language: ruby
rvm:
  - "2.3.0"
before_script:
- sudo apt-get install xvfb
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- bundle install --path vendor/bundle
- bundle exec rake db:create
- bundle exec rake db:migrate

script:
- "xvfb-run -a bundle exec cucumber"
- bundle exec rspec

deploy:
  provider: heroku
  api_key:
    secure: ${API_KEY}

  app:
    master: ${APP_NAME}
    Sprint1: ${TESTAPP_NAME}
    Sprint2: ${TESTAPP_NAME}
    Sprint3: ${TESTAPP_NAME}
    Sprint4: ${TESTAPP_NAME}

 # on:
 #     all_branches: true

  run:
    - "rake heroku:secrets RAILS_ENV=production"
    - "rake db:migrate"
    - "rake assets:precompile"
